name: Push to Podspecs Repo

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest
    
    env:
      RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

    steps:
      - uses: actions/checkout@v2
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: Lint Core
        run: pod lib lint SwedbankPaySDK.podspec
      - name: Lint MB
        run: pod lib lint --include-podspecs=SwedbankPaySDK.podspec SwedbankPaySDKMerchantBackend.podspec
      - name: Push Core
        run: pod trunk push SwedbankPaySDK.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Repo Update
        run: pod repo update
      - name: Push MB
        run: pod trunk push SwedbankPaySDKMerchantBackend.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
