name: Push to Podspecs Repo

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install CocoaPods
      run: gem install cocoapods
    - name: Setup Podspec Repo
      run: pod repo add SPECS https://$PODSPECS_REPO_USER:$PODSPECS_REPO_TOKEN@github.com/SwedbankPay/swedbank-pay-sdk-ios-podspecs.git
      env:
        REPO_USER: ${{ secrets.REPO_USER }}
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Lint
      run: pod lib Lint
    - name: Push
      run: pod repo push SPECS SwedbankPaySDK.podspec
