name: Run Tests

on: push

jobs:
  check:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: pod install
        run: pod install
      - name: Run Tests
        run: xcodebuild -workspace SwedbankPaySDK.xcworkspace -scheme SwedbankPaySDK test
