name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: pod install
        run: pod install
      - name: Run Tests
        run: xcodebuild -workspace SwedbankPaySDK.xcworkspace -scheme SwedbankPaySDK -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' test
