name: Test

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false #if 'true' then one failed job cancels all jobs remaining
      matrix:
        ios: ['14.7', 'latest']
        
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
        run: xcodebuild -scheme SwedbankPaySDK -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=${{ matrix.xcode }}' test
