name: Test

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false #if 'true' then one failed job cancels all jobs remaining
      matrix:
        xcode: ['latest-stable', 'latest', '14.7']
        
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: mxcl/xcodebuild@v1.9.2
        with:
          platform: 'iOS'
          scheme: 'SwedbankPaySDK'
          action: 'test'
          
        #run: xcodebuild -scheme SwedbankPaySDK -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' test
