name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12 #'macos-latest'
    
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests  #${{ matrix.macOS }}
        run: xcodebuild -scheme SwedbankPaySDK -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' test
