name: Test

on: [push]

jobs:
  test:
    runs-on: macos-10.15
    
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Show Available Destinations
        run: xcodebuild -scheme SwedbankPaySDK -showdestinations #-workspace Grocery.xcworkspace 
      
      - name: Run Unit Tests  #${{ matrix.macOS }}
        run: xcodebuild -scheme SwedbankPaySDK -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' test
