name: UI Test

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  ui_test:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Run UI Tests
        run: xcodebuild -scheme SwedbankPaySDKUITestHost -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' test
